// <auto-generated />
using System;
using ComputerApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComputerApi.Migrations
{
    [DbContext(typeof(ComputerContext))]
    [Migration("20241126111600_CreateDb")]
    partial class CreateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ComputerApi.Models.Comp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Display")
                        .HasColumnType("double");

                    b.Property<int?>("Memory")
                        .HasColumnType("int");

                    b.Property<Guid?>("OsId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OsId");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("ComputerApi.Models.OSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OSystem");
                });

            modelBuilder.Entity("ComputerApi.Models.Comp", b =>
                {
                    b.HasOne("ComputerApi.Models.OSystem", "Os")
                        .WithMany("Comps")
                        .HasForeignKey("OsId");

                    b.Navigation("Os");
                });

            modelBuilder.Entity("ComputerApi.Models.OSystem", b =>
                {
                    b.Navigation("Comps");
                });
#pragma warning restore 612, 618
        }
    }
}
